config/routes.rb
Rails.application.routes.draw do

  resources :home
  resources :buyers
  resources :sellers
  resources :stores
  resources :charts
  resources :purchases

  get '/buyer-login' => 'buyer_sessions#new'
  post '/buyer-login' => 'buyer_sessions#create'
  get '/buyer-logout' => 'buyer_sessions#destroy'

  get '/seller-login' => 'seller_sessions#new'
  post '/seller-login' => 'seller_sessions#create'
  get '/seller-logout' => 'seller_sessions#destroy'

  namespace :seller do
    resources :products
  end

  namespace :buyer do
    resources :products
  end

  resources :products

  root 'home#index'

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
    validates :email, uniqueness: true
  
    has_secure_password
end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :store
end

app/controllers/buyer/products_controller.rb
class Buyer::ProductsController < ApplicationController

    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
        @store = Store.find_by(id: @product.store_id)
    end

end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController

    layout 'application'

    def show
        @buyer = Buyer.find(params[:id])
    end

    def edit
        @buyer = Buyer.find(params[:id])
    end

    def new
        @buyer = Buyer.new
    end

    def create
        @buyer = Buyer.new(user_params)

        begin
            if @buyer.save
                flash[:notice] = "Usuário cadastrado."
                redirect_to '/buyer-login'
            else
                flash[:notice] = "Não foi possível completar o cadastro. Usuário já cadastrado."
                redirect_to new_buyer_path
            end
        rescue
            flash[:notice] = "Não foi possível completar o cadastro. Por favor verificar os dados novamente."
            redirect_to new_buyer_path
        end
    end

    def update
        @buyer = Buyer.find(params[:id])
        @buyer.update_attributes(user_params)
        
        if @buyer.save
        flash[:notice] = "Dados atualizados."
        redirect_to home_index_path
        else
        flash[:notice] = "Não foi possível atualizar os dados. Por favor verificar os dados novamente."
        redirect_to edit_buyer_path(@buyer)
        end
    end

    private

    def user_params
      params.require(:buyer).permit(:nome, :email, :cpf, :cnpj,
        :endereco, :numero, :complemento, :bairro, :cep, :cidade, :uf,
        :telresidencial, :telcomercial, :celular,
        :password, :password_confirmation)
    end
end

app/controllers/seller/products_controller.rb
class Seller::ProductsController < ApplicationController

    def index
        @stores = Store.where(seller_id: session[:seller_id])
    end

    def show
        @product = Product.find(params[:id])
        @store = Store.find_by(id: @product.store_id)
    end

    def edit
        @product = Product.find(params[:id])
        @stores = Store.where(seller_id: session[:seller_id])
    end

    def new
        @stores = Store.where(seller_id: session[:seller_id])
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)

        begin
            if @product.save
                flash[:notice] = "Produto cadastrado."
                redirect_to seller_products_path
            else
                flash[:notice] = "Não foi possível completar o cadastro. Por favor verificar os dados novamente."
                redirect_to new_seller_product_path
            end
        rescue
            flash[:notice] = "Não foi possível completar o cadastro. Por favor verificar os dados novamente."
            redirect_to new_seller_product_path
        end
    end

    def update
        @product = Product.find(params[:id])
        @product.update_attributes(product_params)
        
        begin
            if @product.save
                flash[:notice] = "Dados atualizados."
                redirect_to seller_products_path
            else
                flash[:notice] = "Não foi possível atualizar os dados. Por favor verificar os dados novamente."
                redirect_to edit_seller_product_path(@product)
            end
        rescue
            flash[:notice] = "Não foi possível atualizar os dados. Por favor verificar os dados novamente."
            redirect_to edit_seller_product_path(@product)
        end
    end

    def destroy
        @product = Product.find(params[:id])

        @product.destroy
        redirect_to seller_products_path
    end

    private

    def product_params
      params.require(:product).permit(:nome, :codigo, :descricao,
      :preconormal, :precopromocional, :estoqueatual, :estoquemax,
      :store_id)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/buyer/products/index.html.erb
<!-- adicionado o estilo.css -->
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../../css/estilo.css">
    <title>Produtos</title>
</head>

<h1>Produtos</h1>

<% if @products.empty? %>
    Nenhum produto encontrado.
<% else %>
    <% @products.each do |p| %>
    	<!-- BRUNO: Adicionado os <div> para quebrar a linha e colocar espacamento no comeco da linha -->
        <div><b>Nome: </b><%= p.nome %></div>
        <div>&nbsp&nbsp&nbsp Descrição: <%= p.descricao %></div>
        <div>&nbsp&nbsp&nbsp Preço normal: <%= p.preconormal %></div>
        <div>&nbsp&nbsp&nbsp Preço promocional: <%= p.precopromocional %></div>
        <div>&nbsp&nbsp&nbsp <%= link_to "Ver mais detalhes", buyer_product_path(p) %></div>
        <br>
    <% end %>
<% end %>

<br>
<%= link_to "Voltar para página inicial", home_index_path %>

app/views/buyer/products/show.html.erb
<!-- adicionado o estilo.css -->
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../../css/estilo.css">
    <title>Detalhes do produto</title>
</head>

<h1>Detalhes do produto</h1>

    <%= flash[:notice] %>

	<br>

<div>Nome: <%= @product.nome %></div>
<div>Codigo: <%= @product.codigo %></div>
<div>Descricao: <%= @product.descricao %></div>
<div>Preco normal: <%= @product.preconormal %></div>
<div>Preco promocional: <%= @product.precopromocional %></div>
<div>Estoque atual: <%= @product.estoqueatual %></div>
<div>Estoque maximo: <%= @product.estoquemax %></div>


<h2>Loja:</h2>
<div>Nome: <%= @store.nome %></div>
<div>Endereco: <%= @store.endereco %></div>
<div>Numero: <%= @store.numero %></div>
<div>Cidade: <%= @store.cidade %></div>
<div>UF: <%= @store.uf %></div>
<div>Telefone 1: <%= @store.telefone1 %></div>
<div>Telefone 2: <%= @store.telefone2 %></div>

<% number_field(@quantidade, :quantity, in: 1..@product.estoqueatual) %>

<br>
<% if current_buyer %>
    <%= button_to "Adicionar no carrinho", {:controller => "/charts",
    									   :action => "create",
    									   :product_id => @product,
										   :quantidade => @quantidade},
    									   :method => :post %>
<% else %>
<%= link_to "Adicionar no carrinho", '' %>
<b>(É necessário logar como comprador para poder adicionar no carrinho)</b>
<% end %>

<br>
<%= link_to "Voltar para Produtos", buyer_products_path %>