config/routes.rb
Rails.application.routes.draw do

  resources :home
  resources :buyers
  resources :sellers
  resources :stores
  resources :charts
  resources :purchases

  get '/buyer-login' => 'buyer_sessions#new'
  post '/buyer-login' => 'buyer_sessions#create'
  get '/buyer-logout' => 'buyer_sessions#destroy'

  get '/seller-login' => 'seller_sessions#new'
  post '/seller-login' => 'seller_sessions#create'
  get '/seller-logout' => 'seller_sessions#destroy'

  namespace :seller do
    resources :products
  end

  namespace :buyer do
    resources :products
  end

  resources :products

  root 'home#index'

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
    validates :email, uniqueness: true
  
    has_secure_password
end

app/models/chart.rb
class Chart < ActiveRecord::Base
    has_one :product
    belongs_to :buyer
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :store
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
    belongs_to :buyer
end

app/models/purchase_product.rb
class PurchaseProduct < ActiveRecord::Base
    has_one :product
    belongs_to :purchase
end

app/models/seller.rb
class Seller < ActiveRecord::Base
    validates :email, uniqueness: true
  
    has_secure_password
end

app/models/shipping.rb
class Shippping < ActiveRecord::Base
    belongs_to :purchase
end

app/models/shipping_method.rb
class ShipppingMethod < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
    belongs_to :seller
    has_many :products
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController

    layout 'application'

    def show
        @buyer = Buyer.find(params[:id])
    end

    def edit
        @buyer = Buyer.find(params[:id])
    end

    def new
        @buyer = Buyer.new
    end

    def create
        @buyer = Buyer.new(user_params)

        begin
            if @buyer.save
                flash[:notice] = "Usuário cadastrado."
                redirect_to '/buyer-login'
            else
                flash[:notice] = "Não foi possível completar o cadastro. Usuário já cadastrado."
                redirect_to new_buyer_path
            end
        rescue
            flash[:notice] = "Não foi possível completar o cadastro. Por favor verificar os dados novamente."
            redirect_to new_buyer_path
        end
    end

    def update
        @buyer = Buyer.find(params[:id])
        @buyer.update_attributes(user_params)
        
        if @buyer.save
        flash[:notice] = "Dados atualizados."
        redirect_to home_index_path
        else
        flash[:notice] = "Não foi possível atualizar os dados. Por favor verificar os dados novamente."
        redirect_to edit_buyer_path(@buyer)
        end
    end

    private

    def user_params
      params.require(:buyer).permit(:nome, :email, :cpf, :cnpj,
        :endereco, :numero, :complemento, :bairro, :cep, :cidade, :uf,
        :telresidencial, :telcomercial, :celular,
        :password, :password_confirmation)
    end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

    layout 'application'

    def index
        @charts = Chart.where(buyer_id: session[:buyer_id])
    end

    def new
        @chart = Chart.new
    end

    def create
        if @purchase = Purchase.find_by(buyer_id: session[:buyer_id])
            flash[:notice] = "Não foi possível adicionar ao carrinho. Compra em andamento."
            redirect_to buyer_product_path(params[:product_id])
        else
            @chart = Chart.new
            @chart.buyer_id = session[:buyer_id]
            @chart.product_id = params[:product_id]
            @chart.quantidade = params[:quantidade]
            if @chart.save
                flash[:notice] = "Adicionado ao carrinho."
                redirect_to charts_path
            else
                flash[:notice] = "Não foi possível adicionar ao carrinho."
                redirect_to buyer_product_path(params[:product_id])
            end
        end
    end

    def destroy
        @chart = Chart.find(params[:id])
        @chart.destroy
        redirect_to charts_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    layout 'application'

    def show
    end

    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
	<!-- adicionado o estilo.css -->
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="../css/estilo.css">
	<title>E-COMMERCE - LBD</title>
</head>

<h1>E-COMMERCE - LBD</h1>

<% if current_buyer %>
<!-- BRUNO: alterado de <p> para <h2> -->
<h2>
  Bem vindo, <%= current_buyer.nome %>!
</h2>

<%= flash[:notice] %>

	<br>

<%= link_to "Seus dados", edit_buyer_path(current_buyer) %>

<%= link_to "Carrinho", charts_path %>

<%= link_to "Acompanhe sua compra", purchases_path %>

<%= link_to "Sair", '/buyer-logout'%>

<% elsif current_seller %>

<!-- BRUNO: alterado de <p> para <h2> -->
<h2>
  Bem vindo, <%= current_seller.nome %>! <%= link_to "Sair", '/seller-logout'%>
</h2>

<%= flash[:notice] %>

<br>

<%= link_to "Cadastrar uma loja", new_store_path %>

<%= link_to "Veja suas lojas", stores_path(session[:seller_id]) %>

<br>

<%= link_to "Cadastrar um produto", new_seller_product_path %>

<%= link_to "Veja seus produtos", seller_products_path %>

<% else %>

<!-- BRUNO: alterado de <p> para <h2> -->
<h2>
  Bem vindo!
</h2>

<%= link_to "Login", '/buyer-login' %>

<br>

<%= link_to "Cadastre-se", new_buyer_path %>

<%= link_to "Sou vendedor", '/seller-login' %>

<% end %>

<br>

<%= link_to "Produtos", buyer_products_path %>